# .swiftlint.yml
disabled_rules:
  - line_length
  - trailing_whitespace

opt_in_rules: # Manually Enabled
  - empty_count
  - force_unwrapping

excluded: # Excluded directories
  - Carthage
  - Pods
  - .git
  - .build
  - ImageEditor_TestTaskApp

# Line maximal height
line_length:
  warning: 120
  error: 200
